sudo: false 

cache: pip

language: python

notifications:
  email: false

python:
    - 2.7
    - 3.6

script:
    - pip install -r ./requirements.txt
    - pip install python-coveralls
    - yes no | sh build.sh
    - sh tests/run_tests.sh

after_success:
    - coveralls
