sudo: false

cache: pip

language: python

notifications:
  email: false

python:
    - 2.7
    - 3.6

script:
    - sh install_cuda.sh
    - pip install -r ./requirements.txt
    - sh build.sh
    - sh tests/run_tests.sh

after_success:
    - coveralls
