image: Visual Studio 2015
version: 1.0.{build}

build_script:
- cmd: >-
    set PATH=C:\Python37-x64

    pip install -r ./requirements.txt

    pip install mxnet --pre

    pip install python-coveralls nose

    call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

    build.bat

test_script:
- cmd: python -m nose --with-coverage
