image: Visual Studio 2015
version: 1.0.{build}

environment:
    matrix:
        - PYTHON_VERSION: 2.7
          PYTHON_ARCH: "64"

        - PYTHON_VERSION: 3.6
          PYTHON_ARCH: "64"

build_script:
- cmd: >-
    pip --version

    pip install --upgrade pip

    pip --version

    pip install -r ./requirements.txt

    pip install mxnet --pre

    pip install python-coveralls nose

    call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

    build.bat

test_script:
- cmd: python -m nose --with-coverage
