image: Visual Studio 2017
version: 1.0.{build}

environment:
    matrix:
        - PYTHON_VERSION: 2.7
          PYTHON_ARCH: "64"

        - PYTHON_VERSION: 3.6
          PYTHON_ARCH: "64"

build_script:
- cmd: >-
    pip install -r ./requirements.txt

    pip install mxnet-mkl

    pip install python-coveralls nose

    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    build.bat

test_script:
- cmd: python -m nose --with-coverage
